### ISSUE TITLE
Force vacto not working

### ISSUE THREAD

**Issue by danigpc** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#101]
Tested force_vacto with master in roundcube 1.1 and it doesn work. Reason is the following code:

if (!$example)
                                $this->force_vacto = false;

That disables it for most cases. I guess it should be:

if ($example)
                                $this->force_vacto = false;

**Comment by JohnDoh** [comment]
Please describe the issue you are attempting to solve. The code you mention is correct its purpose is to prevent the `sieverules_force_vacto` config option from overriding the parameters of existing rules which it does correctly.

**Comment by JohnDoh** [comment]
no feedback, closing
