### ISSUE TITLE
Howto setup when username requires @%d added to it for login

### ISSUE THREAD

**Issue by TheSin-** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#106]
I can not figure out how to set it up, sieverules, must know to do it from the roundcude config. But manage sieve is only sending the username not the username@%d like I need.

Is this a bug or can I not find the right way to configure this plugin?  I'm trying to move away from sieverules since manage sieve is included in my distro.

**Comment by JohnDoh** [comment]
it is not possible to specify the username in SieveRules, the Roundcube username is always used.

BTW I had a quick look at the managesieve plugin and that does the same thing, so you will have the same issue there.

**Comment by TheSin-** [comment]
This is very odd, I'm using sieverules with the same config and no issues, when I switch to manage sieve I get and login error cause it's sending the username without the _domain_tld.  I used to have to patch manageseive with.

```
--- managesieve.php	2013-12-19 10:12:32.000000000 -0700
+++ /usr/share/roundcube/plugins/managesieve/managesieve.php	2013-10-21 13:39:23.000000000 -0600
@@ -221,7 +221,7 @@
         }
 
         $plugin = $this->rc->plugins->exec_hook('managesieve_connect', array(
-            'user'      => str_replace('@', '_', str_replace('.', '_', $_SESSION['username'])),
+            'user'      => $_SESSION['username'],
             'password'  => $this->rc->decrypt($_SESSION['password']),
             'host'      => $host,
             'port'      => $port,
```

But all he code has changed so I was hoping I wouldn't need to track it down and patch it anymore.  I wonder why sieverules works, I'll dig deeper see what i can find, thanks for looking into it.

**Comment by JohnDoh** [comment]
so there is nothing actually wrong with sieverules, great. i'll close this then.

**Comment by TheSin-** [comment]
I dont' agree with the pre mature closure, since manage sieve works and sieverules does not, which means it's not working sadly, I'm still trying to find the difference.
