### ISSUE TITLE
edit vacation

### ISSUE THREAD

**Issue by mezcalf** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#107]
Hello,

It`s not possible edit message at saved vacation (autoreply) rule. I have tried firefox and chrome.

Version 2.1 is working.

It`s related to versions 2.2 , 2.3 and master.

**Comment by JohnDoh** [comment]
works for me.

what version of Roundcube are you running? version 2.1 of sieverules if for Roundcube 1.0x which runs tinyMCE version 3 and Roundcube 1.1x uses tinyMCE 4 (as does SieveRules 2.2 and above) may be if you are using the wrong version of the plugin for you version of Roundcube and trying to use HTML editor and so you get errors?

**Comment by mezcalf** [comment]
Thank you. It was caused by old version of Roundcube 1.0x

It works with Roundcube 1.1x

Dne 14.5.2015 v 09:47 JohnDoh napsal(a):
