### ISSUE TITLE
Vacation message response to forward sender and not original sender

### ISSUE THREAD

**Issue by Leen15** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#111]
Hi, i've roundcube on a postfix install, and i have several address email (hotmail, gmail, yandex) that automatically forward message to my domain email.
I configurated a vacation message with this plugin but this arrives to my various email address and not to the original sender of email.
This is an example of a test email sent from a temporary email (1rw0b9+4wknkhg@guerrillamail.com) to my gmail account (changed as FORWARDEMAIL@gmail.com) that is automatically forwarded to my domain (luca@MYDOMAIN.com).
In this case, the vacation message arrive to FORWARDEMAIL@gmail.com and not to 1rw0b9+4wknkhg@guerrillamail.com.

> 
Return-Path: <FORWARDEMAIL+caf_=luca=MYDOMAIN.COM@gmail.com>
Delivered-To: <luca@MYDOMAIN.COM>
Received: from MYDOMAIN.COM
    by SERVER (Dovecot) with LMTP id MK69LTow9VVsFgAA471YeA
    for <luca@MYDOMAIN.COM>; Sun, 13 Sep 2015 10:13:46 +0200
Received: from mail-wi0-f180.google.com (mail-wi0-f180.google.com [209.85.212.180])
    by MYDOMAIN.COM (Postfix) with ESMTPS id 9856C4085C
    for <luca@MYDOMAIN.COM>; Sun, 13 Sep 2015 10:13:46 +0200 (CEST)
Received: by wicgb1 with SMTP id gb1so105804134wic.1
    for <luca@MYDOMAIN.COM>; Sun, 13 Sep 2015 01:13:45 -0700 (PDT)
X-Received: by 10.194.20.161 with SMTP id o1mr16474432wje.32.1442132025515;
    Sun, 13 Sep 2015 01:13:45 -0700 (PDT)
X-Forwarded-To: luca@MYDOMAIN.COM
X-Forwarded-For: FORWARDEMAIL@gmail.com luca@MYDOMAIN.COM
Delivered-To: FORWARDEMAIL@gmail.com
Received: by 10.194.26.161 with SMTP id m1csp409771wjg;
    Sun, 13 Sep 2015 01:13:44 -0700 (PDT)
X-Received: by 10.68.233.5 with SMTP id ts5mr19783987pbc.58.1442132024327;
    Sun, 13 Sep 2015 01:13:44 -0700 (PDT)
Received: from guerrillamail.com (mail.guerrillamail.com. [198.143.169.10])
    by mx.google.com with ESMTP id ix1si13925775pac.51.2015.09.13.01.13.42
    for <FORWARDEMAIL@gmail.com>;
    Sun, 13 Sep 2015 01:13:44 -0700 (PDT)
Received-SPF: pass (google.com: domain of 1rw0b9+4wknkhg@guerrillamail.com designates 198.143.169.10 as permitted sender) client-ip=198.143.169.10;
Authentication-Results: mx.google.com;
    spf=pass (google.com: domain of 1rw0b9+4wknkhg@guerrillamail.com designates 198.143.169.10 as permitted sender) smtp.mailfrom=1rw0b9+4wknkhg@guerrillamail.com;
    dkim=pass header.i=@guerrillamail.com;
    dmarc=pass (p=REJECT dis=NONE) header.from=guerrillamail.com
Received: by 198.143.169.10 with HTTP; Sun, 13 Sep 2015 08:13:27 +0000
MIME-Version: 1.0
Message-ID: <5938fc6382ad1902ce526e1a3424f8fa7f77@guerrillamail.com>
Date: Sun, 13 Sep 2015 08:13:27 +0000
To: "FORWARDEMAIL@gmail.com" <FORWARDEMAIL@gmail.com>
From: <1rw0b9+4wknkhg@guerrillamail.com>
Subject: test gmail

And this is my configuration:

![image](https://cloud.githubusercontent.com/assets/3629071/9835987/6d69aaa6-5a05-11e5-8003-28a991803deb.png)

How can i solve this issue?

Thanks

**Comment by JohnDoh** [comment]
I think what you are asking is not possible but you'd have to ask in the sieve community. This is a bug tracker, not a support forum.
