### ISSUE TITLE
Feature Request: IDN encoding

### ISSUE THREAD

**Issue by mgurm** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#112]
Currently, the sieverules plugin apparently does not encode internationalized domain names that occur in sieve conditions or actions. This means that all non-ASCII characters are kept as they are.

For example, domains with german umlauts are stored like this:

```
# rule:[testrule]
if anyof (header :contains "To" "test1@umläut-domain.example.com")
{
        redirect "test2@umläut-domain.example.com";
}
```

They are never transformed to this:

```
# rule:[testrule]
if anyof (header :contains "To" "test1@xn--umlut-domain-icb.example.com")
{
        redirect "test2@xn--umlut-domain-icb.example.com";
}
```

The problem is that it is completely unclear whether the encoding of internationalized domain names should be handled by the tools that generate sieve rules (like this plugin) or by the server-side sieve implementatios themselves. The sieve standard doesn't say anything about this.

However, it would be nice to have this at least as an option, in order to make it work with sieve implementations that don't know what to do with something like `test1@umläut-domain.example.com`.

**Comment by JohnDoh** [comment]
option added in ec0b5b1cb5b928431f360c6826e7f1c83f8af6fb
