### ISSUE TITLE
issue with parsing notify/enotify action after switching from managesieve plugin

### ISSUE THREAD

**Issue by gnanet** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#123]
The regex for parsing the parameters for notify/enotify action does not assume the user was switched from managesieve plugin, this causing the importance to be unset in the UI

Unfortunately managesieve generates the action like this:

`notify :importance "1" :from "SENDEREMAIL" :message "MESSAGE" "mailto:EMAIL";`

**Comment by JohnDoh** [comment]
sieverules can only understand rules it has written. the solution here is to use an import filter to rewrite the rules from the format used by the managesieve plugin to the one used by sieverules.
