### ISSUE TITLE
Filtering to cyrillic folders

### ISSUE THREAD

**Issue by dyubkov** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#125]
When I create some subfolders with cyrillic names and configure filter to move messages there - no messages appear in these folders. Instead, folders with same names encoded in UTF-7 are created, and all messages are going there.

**Comment by JohnDoh** [comment]
are you using the `sieverules_folder_encoding` setting?

**Comment by dyubkov** [comment]
Nope. I wasn't. Thanx for your answer. Changed it to UTF-8 and all works fine now.
