### ISSUE TITLE
Question (not issue)

### ISSUE THREAD

**Issue by boscorelly** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#128]
Hi,

must i use this version or the one at plugins.roundcube.net ?

The one at rc plugins dont add the strop; line to avoid multiple filter use (iwthout, i put a mail in trash and it's re-moved in another folder). # @JohnDoh

**Comment by JohnDoh** [comment]
it does not matter as long as you have the correct version of the plugin for your version of roundcube.
