### ISSUE TITLE
Unable to use plugin with TLSv1.2

### ISSUE THREAD

**Issue by valqk** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#130]
If I disable TLSv1 (1.0,1.1) and only v1.2 is enabled, I get error handshake:
Dovecot logs:
> 
dovecot: managesieve-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=, lip=, TLS handshaking: SSL_accept() failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol, session=<>

In roundcube I just get invalid login.
PHP Error: Unable to connect to managesieve on mail.hostit.bg:4190 in /home/roundcube/roundcubemail-1.1.5/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 216

> PHP Warning:  stream_socket_enable_crypto(): SSL: Connection reset by peer in /rc/vendor/pear-pear.php.net/Net_Sieve/Net/Sieve.php on line 1215
> ERROR: Failed to establish TLS connection (2)
> PHP Error: Unable to connect to managesieve on 185.58.21.214:4190 in /rc/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 216 (GET /rc/roundcubemail-1.1.5/?_task=settings&_action=plugin.managesieve)
> ERROR: Not currently in AUTHORISATION state (1)
> ERROR: Failed to read from socket ()

I didn't have time to debug and check how to enable 1.2 instead of v1 but it should be realtively easy, because roundcube works fine with 1.2.
I've found:

> program/lib/Roundcube/rcube_imap_generic.php:921:                    | 

> $crypto_method = STREAM_CRYPTO_METHOD_TLS_CLIENT
                    | @STREAM_CRYPTO_METHOD_TLSv1_1_CLIENT
                    | @STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT;

> !stream_socket_enable_crypto($this->fp, true, $crypto_method)

This should be passed somewhere in new Net_Sieve or below so pear calls it...

**Comment by JohnDoh** [comment]
what version of net_sieve are you running? i looks like 1.2 is supported see https://github.com/roundcube/Net_Sieve/commit/b2fed3e4933490b7a3c7f9f9d63815c53a72e0e1

**Comment by valqk** [comment]
I've downloaded roundcube LTS 1.1.5
and did composer install from it's default composer.json,
so this means:
"pear-pear.php.net/net_sieve": "~1.3.4",
Maybe roundcube is the correct place to report... hmm... or you should mention this in INSTALL/other doc...

**Comment by JohnDoh** [comment]
if you update to a more recent version of roundcube you'll see in the composer.json file that roundcube's own fork of net_seive is used, not pear's

**Comment by valqk** [comment]
Just looking at this. I'm testing for deployment on prod machine so I choose LTS.
I see. I'll replace net_seive with RC's version.
Although, it's worth mention about this problem-solution, I think.
Thanks.
