### ISSUE TITLE
sieverules_adveditor=1 doesn't provide a UI option to select

### ISSUE THREAD

**Issue by thirstycat** [JohnDoh/Roundcube-Plugin-SieveRules-Managesieve#99]
if I set sieverules_adveditor=2, I get the advanced editor as the default.  However, if I set it to 2 the UI doesn't appear to be any different than the default option of 0.  Just the "friendly" editor and no option to select advanced.

I've tried with both the "Larry" and "Classic" themes.  Running Roundcube 1.0.3 and sieverules 2.2

**Comment by JohnDoh** [comment]
> However, if I set it to 2 the UI doesn't appear to be any different than the default option of 0.

I assume that should have said 1.

When set to mode 1 the UI will essentially look the same as 0 but at the bottom of the filters list you should see a little gear icon, pressing that will bring up a menu and you should see an option for Adcanced Editor.

> Running Roundcube 1.0.3 and sieverules 2.2

For Roundcube 1.0.x you should be running Sieverules 2.1, 2.2 needs version 1.1 of Roundcube.

**Comment by thirstycat** [comment]
got it!  thanks... I missed that icon... and as you pointed out, sieverules 2.2 wasn't quite usable with the old version of Roundcube.  I updated to 1.1 and all is good.  thanks!!
